### PR TITLE
add pricing table

### PR DESCRIPTION
**Pull request by yhlukhov**
Created pricing table for chickens at the bottom of main page

### CODE REVIEW

**Comment by yhlukhovukr** [comment]
Please, make simple update to the title

**Review by yhlukhovukr — COMMENTED** [review]
Simple comment: update header of the table

**Comment by yhlukhov** [comment]
> Simple comment: update header of the table

done

**Comment by yhlukhovukr** [comment]
> > Simple comment: update header of the table
> 
> done

reviewed

**Comment by yhlukhov** [comment]
Hey, we still want to merge it

**Review by yhlukhovukr — CHANGES_REQUESTED** [review]
change header please

**Comment by yhlukhov** [comment]
> change header please

done

**Pull request merged**
